### ISSUE TITLE
pyzor

### ISSUE THREAD

**Issue by jranma** [cgt/rspamd-plugins#4]
Hi, 
Thanks for the plugins for rspamdn, very useful !
Do you know why pyzor support has not been included to rspamd extrenal modules, but razor was ? 

Now I'm trying to find out if pyzor works. I haven't encountered any spam that has been detected by pyzor yet, which surprises me a bit, but I've recently installed it. Since PYZOR doesn't add a header in case of ham, it's hard to know if the mail has passed through their server. 

Do you by chance have an example of a message that triggers pyzor? I can't use GTUBE because rspmand blocks it as input. 

Normally a completely empty mail is considered as spam by pyzor. But when I send an empty mail, I get this error: 
`2021-01-31 09:43:41 #37894(normal) <7a317b>; lua; pyzor.lua:18: request error: IO read error: connection terminated`

cheers

**Comment by jranma** [comment]
oh yes, Just got a spam caught by pyzor, nice !
`PYZOR(4.00)[count=10 wl=0];`

**Comment by cgt** [comment]
> Do you know why pyzor support has not been included to rspamd extrenal modules, but razor was ?

I do not. I haven't kept up with recent developments in Rspamd, so I wasn't aware that they'd added Razor support.

>oh yes, Just got a spam caught by pyzor, nice !

Glad to hear it's working for you.
